control_interface: ens2f0
control_network: 
control_network_prefix: 24
control_network_start: 20

public_ip_interface: ens2f3
public_ip_network: 
public_ip_network_prefix: 25
public_ip_network_node_start: 15 
public_ip_gateway: 
public_ip_dns_resolver:
# ip addresses will be used by vm
public_ip_vm_start: 30
# bridge will be used by vms
public_bridge_name: br0

# starting port of bmc on each machine
vmhost_bmc_port: 9000

# domain used for sno clusters
sno_cluster_name_domain: 

# hub config file directory, will be used on localhost
hub_config_dir: /tmp/hub-config
# vmhost configfile directory, will be used on vmhost
vmhost_config_dir: /tmp/vmhost-config

# localhost path for kubeconfig
hub_kubeconfig_path:

# dockerconfig.json file path, expect to be on localhost
pull_secret_path:

# path for ssh private key, expect to be on localhost
ssh_key_path: 

# a placeholder to make bmh happy, should be base64 encoded, will actually not be used anywhere
bmc_password_base64: 
bmc_username_base64: 
