control_interface: ens2f0
control_network: 
control_network_prefix: 24
control_network_start: 20

public_ip_interface: ens2f3
public_ip_network: 
public_ip_network_prefix: 25
public_ip_network_node_start: 15 
public_ip_gateway: 
public_ip_dns_resolver:
# ip addresses will be used by vm
public_ip_vm_start: 30
# bridge will be used by vms
public_bridge_name: br0

# starting port of bmc on each machine
vmhost_bmc_port: 9000

# domain used for sno clusters
sno_cluster_name_domain: 

# hub config file directory
hub_config_dir: /tmp/hub-config

vmhost_config_dir: /tmp/vmhost-config

# 
hub_kubeconfig_path:


