# Copyright Contributors to the Open Cluster Management project

---
# node-network tasks

- name: Stop iptables
  service: name=iptables state=stopped

- name: Disbale on iptable on boot
  service: name=iptables enabled=no

- name: setup bridge for public ip interface
  nmcli:
    type: bridge
    conn_name: "{{ public_bridge_name }}"
    ifname: "{{ public_bridge_name }}"
    ip4: "{{ public_ip_network | next_nth_usable(public_ip_network_node_start  +  hostvars[inventory_hostname].offset) }}/{{ public_ip_network_prefix }}"
    state: present

- name: delete slave interface if exist
  command: bash -c "nmcli con delete {{ public_ip_interface }}-slave "
  ignore_errors: yes
  
- name: bind interface with bridge
  command: bash -c "nmcli con add type bridge-slave con-name {{ public_ip_interface }}-slave ifname {{ public_ip_interface }} master {{ public_bridge_name }} "

- name: disable old interface
  command: bash -c "nmcli con down {{public_ip_interface}}"
  ignore_errors: yes

- name: enable bridge & slave
  command: bash -c "nmcli con up {{ public_bridge_name }} && nmcli con up  {{public_ip_interface}}-slave "