- name: destroy vm
  shell: |
    virsh destroy {{sno_cluster_name}}

- name: select disk folder base nvme or sda 
  set_fact:
    sno_vm_disk_dir: "{% if ( enable_nvme  and use_nvme ) %}{{nvme_mount_path}}/libvirt/images{% else %}/var/lib/libvirt/images{% endif %}"

- name: delete disk file
  shell: |
    rm "{{sno_vm_disk_dir}}/{{ sno_cluster_name }}.qcow2"

- name: undefine vm
  shell: |
    virsh undefine --nvram {{sno_cluster_name}}
