# Copyright Contributors to the Open Cluster Management project

apiVersion: agent-install.openshift.io/v1beta1
kind: infraenv
metadata:
  name: CLUSTER_NAME
  namespace: CLUSTER_NAME
spec:
  clusterRef:
    name: CLUSTER_NAME
    namespace: CLUSTER_NAME
  sshAuthorizedKey: SSH_PUBLIC_KEY
  agentLabelSelector:
    matchLabels:
      bla: aaa
  pullSecretRef:
    name: assisted-deployment-pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      acm-ai-sno-test-CLUSTER_NAME: CLUSTER_NAME