apiVersion: agent-install.openshift.io/v1beta1
kind: InstallEnv
metadata:
  name: CLUSTER_NAME
  namespace: CLUSTER_NAME
spec:
  clusterRef:
    name: CLUSTER_NAME
    namespace: CLUSTER_NAME
  sshAuthorizedKey: SSH_PUBLIC_KEY
  agentLabelSelector:
    matchLabels:
      bla: aaa
  pullSecretRef:
    name: assisted-deployment-pull-secret