

# interface of the public ip address we will use as the bridge of vms
# note is doesn't have to be real public
# as long as this interface will be reachable from the hub in both direction, we will be good
public_ip_interface: ens2f3
# ip network to connect with hub, should make sure hub & this network can reach each other
public_ip_network: 
# prefix of the public ip network, should match public_ip_network
public_ip_network_prefix: 
# start of vmhost's node IP address, final will be public_ip_network_node_start+offset
public_ip_network_node_start: 
# gateway of public ip address
public_ip_gateway: 
# default dns resolver of the network, will be used to look for hub
public_ip_dns_resolver: 

# bridge name will be used by vms, and we will create this bridge in the vmhost
# the public_ip_interface will be a slave of this bridge
public_bridge_name: br0

# ip addresses will be used by vm
public_ip_vm_start: 30

# starting port of bmc on each machine
vmhost_bmc_port: 9000

# domain used for sno clusters
sno_cluster_name_domain: 

# hub config file directory, will be used on localhost
hub_config_dir: /tmp/hub-config
# vmhost configfile directory, will be used on vmhost
vmhost_config_dir: /tmp/vmhost-config

# localhost path for kubeconfig
hub_kubeconfig_path:

# path for ssh  keys, expect to be on localhost
ssh_private_key_path:
ssh_public_key_path:

# a placeholder to make bmh happy, should be base64 encoded, will actually not be used anywhere
bmc_password_base64: "{{ 'password' | b64encode }}"
bmc_username_base64: "{{ 'redhat' | b64encode }}"

# patch will be mounted on vm host
disk2_mount_path: /mnt/disk2

# The mac address prefix of the 
vm_mac_address_prefix: "52:54:00:76"

# vm resource settings
# make sure they are not exceeding the vmhost's capacity
vm_cpu: 6
# unit GiB
vm_memory: 32
# unit G
vm_disk: 120
