- name: Install libvirt 
  service: name=iptables state=stopped
  yum:
    name:
    - ansible
    - git
    - jq
    - tmux
    - net-tools
    - tcpdump
    - iproute-tc
    state: present
    update_cache: true
    disable_gpg_check: yes