- name: check if hub_config_dir exists
  stat:
    path: "{{hub_config_dir}}"
  register: hcdir

- block:
  - name: check if hub_config_dir/vm_inventory.csv exists
    stat:
      path: "{{hub_config_dir}}/vm_inventory.csv"
    register: hcfile

  - name: delete file if pre existed
    file:
      path: "{{hub_config_dir}}/vm_inventory.csv"
      state: absent
    when: hcfile.stat.exists
  when: hcdir.stat.exists

- name: create hub_config_directory if it doesn't exist
  file:
    path: "{{hub_config_dir}}"
    state: directory
  when: not hcdir.stat.exists

- name: create file
  file:
    path: "{{hub_config_dir}}/vm_inventory.csv"
    state: touch

- name: create first line
  lineinfile:
    path: "{{hub_config_dir}}/vm_inventory.csv"
    insertafter: EOF
    line: "cluster_name,domain_name,mac_addr,ip,prefix,gateway,machine_cidr,dns_resolver,bmc_addr,bmc_username,bmc_password"
- name: set a counter
  set_fact:
    line_counter=0
- name: create inventory
  include_tasks: append-one-vmhost.yml
  loop: "{{ groups['vmhosts'] }}"
  loop_control:
    loop_var: vmhost_name

- name: sort inventory
  shell: |
    cat {{hub_config_dir}}/vm_inventory.csv | sort -t ':' -k 6 > {{hub_config_dir}}/vm_inventory_sorted.csv
