# Copyright Contributors to the Open Cluster Management project

apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 namespace: assisted-installer
 name: agent
spec:
 databaseStorage:
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 20Gi
  volumeName: PV_AI_POSTGRES
 filesystemStorage:
  volumeName: PV_AI_BUCKET
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 120Gi