apiVersion: v1
kind: PersistentVolume
metadata:
  name: PV_AI_POSTGRES
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres
    namespace: assisted-installer
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODE_HOST_NAME